#!/usr/bin/env python3
"""Starter node for the Lunabotics ROS 2 case study.

Fill in TASKS 1-3 here. See README.md for the full description of each task.

Run it with:

    ros2 run move publisher

As shipped this node starts, spins, and does nothing -- that is intentional. Use it to
confirm your workspace is built and sourced before you write any logic.

Each task is marked with a TASK n.n comment matching the README. Commented-out lines are
deliberate: uncomment and complete them.
"""

import math

import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data

from geometry_msgs.msg import Twist, Pose, Vector3, Point, Quaternion
from nav_msgs.msg import Odometry
from sensor_msgs.msg import PointCloud2
from sensor_msgs_py import point_cloud2
from std_msgs.msg import Float64

from scipy.interpolate import Akima1DInterpolator
import numpy as np


class RobotController(Node):
    """Drives the robot, tracks its position error, and flags obstacles."""

    def __init__(self):
        super().__init__('robot_controller')

        # Publish to /error when the position delta exceeds this (TASK 2.3).
        # This is a starting value -- justify whatever you settle on.
        self.error_thresh = 0.5

        # ---- TASK 1.2: publisher that drives the robot ---------------------
        # Which topic moves the robot? Find it first (TASK 1.1), then uncomment.
        
        self.move_pub = self.create_publisher(Twist, '/cmd_vel', 10)

        # ---- TASK 1.3: the path you chose ----------------------------------
        # Pick a route that gets the robot around the wall, and represent it
        # however you think is best -- a list of waypoints, a sequence of
        # timed velocity commands, a parametric curve, something else.
        #
        # Document HERE why you chose this path and this representation.
        # That reasoning is a large part of what we are evaluating.


        """
        I've chosen to represent the path around the wall via waypoints that only store positional and rotational targets.
        This route has 4 points, including a starting pose, intermediate waypoints, and an end goal.
        The reason for this idea is to abstract the high-level goals/objectives of the robot's pathfinding into simple positional targets, 
        and allow lower-level implementations to construct their own trajectories, constraints, and path following algorithms. I could also pair this
        with additional data per point, such as a desired velocity target, but from watching some Lunabotics videos, every robot drive action starts
        without being in motion and ends up in a state without motion. The only use case for velocity targets (probably) is if you want the robot to
        shovel moon dirt while driving, meaning the robot would have its velocity constrained to not go too fast.
        
        For example, this high-level path could be generated by a pathfinding algorithm that utilizes LiDAR data to find the shortest 3d path between
        obstacles to an objective. This gives whatever low level implementation of pathfollowing and trajectory generation we choose
        lots of freedom to do what they want with this data. Furthermore, this representation is super generalizable and easy to modify, visualize, 
        and analyze for anyone that may work with this data. It also gives a lot more flexibility and robustness compared to a time-parametrized,
        velocity-parametrized, or parametric curve, because if for example the robot gets knocked off course, it can just find the next point on the
        path to drive to, and generate a new trajectory on the fly based on the remaining points, instead of following a rigidly defined definition of 
        a path. 

        An example of a low-level implementation could just be a simple drive-to-point PID controller for our robot (i'm assuming it's a tank drive). 
        The robot would rotate via PID to a desired heading, drive forward with a PID loop based off odometry, 
        reach the desired position, and rotate one last time to match the end rotational target. For every point in the path, the robot would just use 
        this drive-to-point to complete the path. This is already a pretty robust (albeit simple) way to complete autonomous routines, as the PID on the 
        heading and translation could help account for wheel slip/tread slip, and hopefully the localization can help ensure our robot actually gets to 
        the correct pose.

        Another example of a low-level implementation could be a trajectory generator. This could take in the path of points and create a 
        trajectory based on any number of techniques (splines, polynomials, etc). Then you would use a differential PID controller to follow each of 
        the position, velocity, and acceleration values at each time step of the path. One issue with this however, is that if the robot ever falls behind/
        doens't meet the position, velocity, and acceleration values at a certian time step, then the PID controllers may fight with each other & create
        unintended behavior.

        For more advanced paths however, one could add in control points for Bezier curves for more precise control of pathing as well, but that would require 
        adding more poses and data to store the control points.
        """

        # Anyways thanks for reading all that, here's the implementation lol:
        initial = Pose(position=Point(x=0.0, y=0.0, z=0.0), quaternion=Quaternion()) 
        point1  = Pose(position=Point(x=5.0, y=10.0, z=0.0), quaternion=Quaternion())
        end     = Pose(position=Point(x=15.0, y=0.0, z=0.0), quaternion=Quaternion())
        self.path = [initial, point1, end]
        self.generate_spline(self.path, 2.0)

        # Then drive it on a timer:
        self.prev_yaw   = 0.0
        self.start_time = self.get_clock().now()
        self.move_timer = self.create_timer(0.1, self.send_move_cmd)

        # ---- TASK 2.2: subscriber for the robot's 6D pose ------------------
        # One of the two onboard sensors reports 6D data. Find it (TASK 2.1).
        #
        self.robot_pos_sub = self.create_subscription(
            Odometry,
            "/model/vehicle_blue/odometry",
            self.on_robot_pos,
            qos_profile_sensor_data,
        )
        self.error_pub = self.create_subscription(
            Float64,
            "/error",
            lambda x: None,
            qos_profile_sensor_data  
        )

        # ---- TASK 2.3: where the measured-vs-actual error goes -------------
        # self.error_pub = self.create_publisher(Float64, '/error', 10)
        #
        # Hint: ground truth for "actual" is published by the simulator on the
        # robot's odometry topic (nav_msgs/Odometry). Deciding what to compare,
        # and in which frame, is part of the task.

        # ---- TASK 3: lidar in, filtered obstacles out ----------------------
        # The lidar has a single vertical sample, so this cloud is one flat
        # row of points at the sensor's height -- not a 3D volume.
        #
        # self.lidar_sub = self.create_subscription(
        #     PointCloud2,
        #     '/lidar/points',
        #     self.on_lidar,
        #     qos_profile_sensor_data,
        # ) 
        # self.obstacle_pub = self.create_publisher(
        #     PointCloud2, '/obstacle_cloud', 10)

        self.get_logger().info(
            'robot_controller started (scaffold -- nothing wired up yet)')

    # -----------------------------------------------------------------------
    # TASK 1.2 -- publish a velocity command
    # -----------------------------------------------------------------------
    def calc_distance(self, pose1: Pose, pose2: Pose): 
        pos1 = pose1.position
        p1 = np.array([pos1.x, pos1.y, pos1.z])
        pos2 = pose2.position
        p2 = np.array([pos2.x, pos2.y, pos2.z])
        return np.linalg.norm(p1 - p2)

    def generate_spline(self, path, max_vel=2.0): # I've decided to go with a trajectory generator instead of a drive-to-point (cuz it sounds cooler)
        times = [0.0]
        for i in range(1, len(path)):
            times.append(self.calc_distance(path[i], path[i-1]) / max_vel + times[i-1])

        coords = np.array([[p.position.x, p.position.y, p.position.z] for p in path])
        times = np.array(times, dtype=float)

        self.interp_x = Akima1DInterpolator(times, coords[:, 0])
        self.interp_y = Akima1DInterpolator(times, coords[:, 1])
        self.interp_z = Akima1DInterpolator(times, coords[:, 2])

    def send_move_cmd(self):
        """Publish one Twist that moves the robot along self.path.

        TODO: build the Twist and publish it on self.move_pub.
        """

        elapsed = (self.get_clock().now() - self.start_time).nanoseconds / 1e9
        vx = float(self.interp_x(elapsed, 1))
        vy = float(self.interp_y(elapsed, 1))
        vz = float(self.interp_z(elapsed, 1))

        if math.isnan(vx) or math.isnan(vy) or math.isnan(vz):
            vx = 0
            vy = 0
            vz = 0

        target_yaw = math.atan2(vy, vx)
        delta_yaw = target_yaw - self.prev_yaw
        delta_yaw = -math.atan2(math.sin(delta_yaw), math.cos(delta_yaw))

        # Robot centric drive
        local_vx = vx * math.cos(target_yaw) + vy * math.sin(target_yaw)
        local_vy = -vx * math.sin(target_yaw) + vy * math.cos(target_yaw)
        local_vz = vz

        print(local_vx, local_vy, local_vz, target_yaw)

        twist = Twist(linear=Vector3(x=float(local_vx), y=float(local_vy), z=float(local_vz)), angular=Vector3(x=0.0, y=0.0, z=float(delta_yaw)))

        self.move_pub.publish(twist)

    # -----------------------------------------------------------------------
    # TASK 2.3 -- compare reported position against ground truth
    # -----------------------------------------------------------------------
    def on_robot_pos(self, msg):
        """Compare the sensor's idea of where we are against the truth.

        Publish a Float64 on self.error_pub when the delta exceeds
        self.error_thresh.

        TODO: decide what "delta" means here and justify it in a comment.
        """
        print(msg)

        delta = 0.0
        if delta > self.error_thresh:
                error_msg = Float64()
                error_msg.data = float(delta)
                self.error_pub.publish(error_msg)
    # -----------------------------------------------------------------------
    # TASK 3.3 -- classify a single lidar point
    # -----------------------------------------------------------------------
    def is_obstacle(self, point):
        """Return True if `point` is something we must avoid.

        The barrier is passable -- treat it like dust in the air. The poles are
        not. `point` is an (x, y, z) tuple in the lidar's frame.

        TODO: decide what separates a pole from the barrier and implement it.
        """
        raise NotImplementedError('TASK 3.3')

    # -----------------------------------------------------------------------
    # TASK 3.2 -- filter the scan and republish what matters
    # -----------------------------------------------------------------------
    def on_lidar(self, msg):
        """Filter incoming points through is_obstacle and republish.

        point_cloud2.read_points(msg, field_names=('x', 'y', 'z')) iterates the
        cloud; point_cloud2.create_cloud_xyz32(msg.header, pts) builds the
        outgoing one.

        TODO: keep only the obstacle points and publish on self.obstacle_pub.
        """
        raise NotImplementedError('TASK 3.2')


def main(args=None):
    rclpy.init(args=args)
    node = RobotController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
